from PIL import Image, ImageFilter, ImageEnhance
with Image.open("download.jpg") as photo:
    print(photo.size)
    print(photo.format)
    print(photo.mode)
    photo.show()
    photo_left_90 = photo.transpose(Image.ROTATE_90)
    photo_left_90.save("download_left_90.jpg")
    photo_left_270 = photo.transpose(Image.ROTATE_270)
    photo_left_270.save("download_left_270.jpg")
    photo_flip = photo.transpose(Image.FLIP_LEFT_RIGHT)
    photo_flip.save("download_flip.jpg")
    photo_blur = photo.filter(ImageFilter.BLUR)
    photo_blur.save("download_blur.jpg")
    photo_box_blur = photo.filter(ImageFilter.BoxBlur(10))
    photo_box_blur.save("download_box_blur.jpg")
    photo_gaus_blur = photo.filter(ImageFilter.GaussianBlur(10))
    photo_gaus_blur.save("download_gaus_blur.jpg")
    photo_BW = photo.convert("L")
    photo_BW.save("download_BW.jpg")
    photo_crop = photo.crop((40, 50, 120, 65))
    photo_crop.save("download_crop.jpg")
    photo_size = photo.resize((100, 100))
    photo_size.save("download_size.jpg")